apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.name" . }}
  labels:
    app: {{ include "microservice.name" . }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '{{ .Values.service.port }}'
spec:
  selector:
    app: {{ include "microservice.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
