apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog
  namespace: loans
spec:
  project: default

  source:
    repoURL: https://github.com/osber1/loans-infra
    targetRevision: HEAD
    path: k8s/infra
    directory:
      include: mailhog.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: loans

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true