apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: loans
  labels:
    app: fluent-bit

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit
roleRef:
  kind: ClusterRole
  name: fluent-bit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: loans

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: loans
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  /fluent-bit/etc/parsers.conf
    @INCLUDE my-input.conf
    @INCLUDE filter.conf
    @INCLUDE output-elasticsearch.conf

  my-input.conf: |
    [INPUT]
        Name              tail
        Tag               services.*
        Path              /var/log/containers/notification*.log,/var/log/containers/risk*.log,/var/log/containers/back*.log
        multiline.parser  docker, cri
        DB                /fluent-bit/tail-services-state.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Buffer_Max_Size   256k
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/notification*.log,/var/log/containers/risk*.log,/var/log/containers/back*.log
        multiline.parser  docker, cri
        DB                /fluent-bit/tail-containers-state.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Buffer_Max_Size   256k

  filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               *
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       service_log
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  output-elasticsearch.conf: |
    [OUTPUT]
        Name                es
        Match               services.*
        Host                ${FLUENT_ELASTICSEARCH_HOST}
        Port                ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format     On
        Logstash_Prefix     fluent-bit-services
        Replace_Dots        On
        Retry_Limit         False
        Time_Key            @timestamp
        Suppress_Type_Name  On

    [OUTPUT]
        Name                es
        Match               kube.*
        Host                ${FLUENT_ELASTICSEARCH_HOST}
        Port                ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format     On
        Logstash_Prefix     fluent-bit-infra
        Replace_Dots        On
        Retry_Limit         False
        Time_Key            @timestamp
        Suppress_Type_Name  On

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Keep   Off
        Time_Key    @timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Decode_Field_As   escaped   message
        Decode_Field_As   escaped   stack_trace
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: loans
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:3.0
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch.loans.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.conf
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/conf
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # Mount custom config
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
