apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loans
  name: mailhog
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:v1.0.1
          ports:
            - name: http
              containerPort: 8025
              protocol: TCP
            - name: client
              containerPort: 1025
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: loans
  name: mailhog
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - name: http
      protocol: TCP
      port: 8025
      targetPort: http
    - name: tcp-mail
      protocol: TCP
      port: 1025
      targetPort: 1025

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailhog-ingress
  namespace: loans
spec:
  ingressClassName: nginx
  rules:
    - host: mailhog.osber.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailhog
                port:
                  number: 8025