apiVersion: v1
kind: Secret
metadata:
  namespace: loans
  name: pgadmin-secret
type: Opaque
data:
  pgadmin_default_email: YWRtaW5AYWRtaW4uY29t
  pgadmin_password: YWRtaW4=

---

kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: loans
  name: pgadmin-pv-volume
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/pgadmin"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: loans
  name: pgadmin-pv-claim
  labels:
    app: pgadmin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loans
  labels:
    app: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - image: dpage/pgadmin4:8.4
          imagePullPolicy: Always
          name: pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin_default_email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin_password
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-storage
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [ "sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin" ]
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  namespace: loans
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: loans
spec:
  ingressClassName: nginx
  rules:
    - host: pgadmin.osber.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80