apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loans
  name: rabbitmq-conf
  labels:
    name: rabbitmq-conf
data:
  rabbitmq.conf: |-
    management.load_definitions = /etc/rabbitmq/definitions.json

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loans
  name: rabbitmq-definitions
  labels:
    name: rabbitmq-definitions
data:
  definitions.json: |-
    {
      "users": [
        {
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "limits": {},
          "name": "guest",
          "password_hash": "bcUJV81RZ62Zy8MChFFWIwalB8LrXZZfkrBZb8kBVez6SLWM",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "\/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "queues": [
        {
          "name": "notification.queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [
        {
          "name": "internal.exchange",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "internal.exchange",
          "vhost": "/",
          "destination": "notification.queue",
          "destination_type": "queue",
          "routing_key": "internal.notification.routing-key",
          "arguments": {}
        }
      ]
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: loans
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.2-management-alpine
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
            - containerPort: 15692
              name: prometheus
          volumeMounts:
            - name: rabbitmq-definitions-config-map
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
            - name: rabbitmq-conf-config-map
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: rabbitmq-conf-config-map
          configMap:
            name: rabbitmq-conf
        - name: rabbitmq-definitions-config-map
          configMap:
            name: rabbitmq-definitions

---

apiVersion: v1
kind: Service
metadata:
  namespace: loans
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      name: http
    - port: 5672
      name: amqp
    - port: 15692
      name: prometheus

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: loans
spec:
  ingressClassName: nginx
  rules:
    - host: rabbitmq.osber.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672