global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'back_office'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'back-office:8080' ]
        labels:
          application: 'Back-office Application'
  - job_name: 'back_office_local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]
        labels:
          application: 'Back-office Application'