nameOverride: fluent-bit

rbac:
  create: true

daemonset:
  enabled: true

config:
  customParsers: |
    [PARSER]
        Name        json
        Format      json
        Time_Keep   Off
        Time_Key    @timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Decode_Field_As   escaped   message
        Decode_Field_As   escaped   stack_trace

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

  inputs: |
    [INPUT]
        Name              tail
        Tag               services.*
        Path              /var/log/containers/notification*.log,/var/log/containers/risk*.log,/var/log/containers/back*.log
        multiline.parser  docker, cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Buffer_Max_Size   256k

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/notification*.log,/var/log/containers/risk*.log,/var/log/containers/back*.log
        multiline.parser  docker, cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Buffer_Max_Size   256k

  outputs: |
    [OUTPUT]
        Name                es
        Match               services.*
        Host                elasticsearch.loans.svc.cluster.local
        Port                9200
        Logstash_Format     On
        Logstash_Prefix     fluent-bit-services
        Replace_Dots        On
        Retry_Limit         False
        Time_Key            @timestamp
        Suppress_Type_Name  On

    [OUTPUT]
        Name                es
        Match               kube.*
        Host                elasticsearch.loans.svc.cluster.local
        Port                9200
        Logstash_Format     On
        Logstash_Prefix     fluent-bit-infra
        Replace_Dots        On
        Retry_Limit         False
        Time_Key            @timestamp
        Suppress_Type_Name  On

  filters: |
    [FILTER]
        Name                kubernetes
        Match               *
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       service_log
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
